### ISSUE TITLE
Jellyfin 10.7.0 Compatibility

### ISSUE THREAD

**Issue by Protektor-Desura** [n0tMaster/n0tFlix-Main#5]
None of the channel plugins are compatible with Jellyfin 10.7.0. I suspect the other plugins have issues as well.

**Comment by capic** [comment]
Hello @n0tMaster ,

same here, impossible to install.

```
Emby.Server.Implementations.Updates.InstallationManager: Package installation failed
System.IO.InvalidDataException: The checksum of the received data doesn't match.
   at Emby.Server.Implementations.Updates.InstallationManager.PerformPackageInstallation(InstallationInfo package, PluginStatus status, CancellationToken cancellationToken)
   at Emby.Server.Implementations.Updates.InstallationManager.PerformPackageInstallation(InstallationInfo package, PluginStatus status, CancellationToken cancellationToken)
   at Emby.Server.Implementations.Updates.InstallationManager.InstallPackageInternal(InstallationInfo package, CancellationToken cancellationToken)
   at Emby.Server.Implementations.Updates.InstallationManager.InstallPackage(InstallationInfo package, CancellationToken cancellationToken)
[2021-06-17 09:53:24.856 +02:00] [ERR] [139] Jellyfin.Server.Middleware.ExceptionMiddleware: Error processing request. URL "POST" "/Packages/Installed/Addic7ed%20Subtitles".
System.IO.InvalidDataException: The checksum of the received data doesn't match.
   at Emby.Server.Implementations.Updates.InstallationManager.PerformPackageInstallation(InstallationInfo package, PluginStatus status, CancellationToken cancellationToken)
   at Emby.Server.Implementations.Updates.InstallationManager.PerformPackageInstallation(InstallationInfo package, PluginStatus status, CancellationToken cancellationToken)
   at Emby.Server.Implementations.Updates.InstallationManager.InstallPackageInternal(InstallationInfo package, CancellationToken cancellationToken)
   at Emby.Server.Implementations.Updates.InstallationManager.InstallPackage(InstallationInfo package, CancellationToken cancellationToken)
   at Emby.Server.Implementations.Updates.InstallationManager.InstallPackage(InstallationInfo package, CancellationToken cancellationToken)
   at Jellyfin.Api.Controllers.PackageController.InstallPackage(String name, Nullable`1 assemblyGuid, String version, String repositoryUrl)
   at lambda_method30516(Closure , Object )
   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.TaskOfActionResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeActionMethodAsync>g__Awaited|12_0(ControllerActionInvoker invoker, ValueTask`1 actionResultValueTask)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeInnerFilterAsync>g__Awaited|13_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeNextResourceFilter>g__Awaited|24_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Rethrow(ResourceExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeFilterPipelineAsync>g__Awaited|19_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
   at Jellyfin.Server.Middleware.ServerStartupMessageMiddleware.Invoke(HttpContext httpContext, IServerApplicationHost serverApplicationHost, ILocalizationManager localizationManager)
   at Jellyfin.Server.Middleware.WebSocketHandlerMiddleware.Invoke(HttpContext httpContext, IWebSocketManager webSocketManager)
   at Jellyfin.Server.Middleware.IpBasedAccessValidationMiddleware.Invoke(HttpContext httpContext, INetworkManager networkManager)
   at Jellyfin.Server.Middleware.LanFilteringMiddleware.Invoke(HttpContext httpContext, INetworkManager networkManager, IServerConfigurationManager serverConfigurationManager)
   at Microsoft.AspNetCore.Authorization.Policy.AuthorizationMiddlewareResultHandler.HandleAsync(RequestDelegate next, HttpContext context, AuthorizationPolicy policy, PolicyAuthorizationResult authorizeResult)
   at Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)
   at Swashbuckle.AspNetCore.ReDoc.ReDocMiddleware.Invoke(HttpContext httpContext)
   at Swashbuckle.AspNetCore.SwaggerUI.SwaggerUIMiddleware.Invoke(HttpContext httpContext)
   at Swashbuckle.AspNetCore.Swagger.SwaggerMiddleware.Invoke(HttpContext httpContext, ISwaggerProvider swaggerProvider)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at Jellyfin.Server.Middleware.RobotsRedirectionMiddleware.Invoke(HttpContext httpContext)
   at Jellyfin.Server.Middleware.LegacyEmbyRouteRewriteMiddleware.Invoke(HttpContext httpContext)
   at Microsoft.AspNetCore.ResponseCompression.ResponseCompressionMiddleware.Invoke(HttpContext context)
   at Jellyfin.Server.Middleware.ResponseTimeMiddleware.Invoke(HttpContext context)
   at Jellyfin.Server.Middleware.ExceptionMiddleware.Invoke(HttpContext context)
```

Any Idea?

**Comment by C-Fu** [comment]
Tried installing one. Restarting JF afterwards caused My Plugins section to not load anymore.

**Comment by MaDTaZ** [comment]
Was wonder if you were going to get them compatible on 10.7 and 10.8?

**Comment by Protektor-Desura** [comment]
I am guessing that the author has given up on keeping these plugins updated sadly.

**Comment by MaDTaZ** [comment]
> I am guessing that the author has given up on keeping these plugins updated sadly.

Yes that is what I figured as well.

**Comment by TheOddPirate** [comment]
Ah wow, thanks for the feedback, stopped developing the plugins when i started school and havent touched jellyfin since, but its time for my winter vacation now and was thinking maybe see whats new with jellyfin so maybe il try and do a update. 

My main plan was a torrent downloader and a torrent  searcher so i dont need more and more space to save my shows

**Comment by Protektor-Desura** [comment]
> Ah wow, thanks for the feedback, stopped developing the plugins when i started school and havent touched jellyfin since, but its time for my winter vacation now and was thinking maybe see whats new with jellyfin so maybe il try and do a update.
> 
> My main plan was a torrent downloader and a torrent searcher so i dont need more and more space to save my shows

So does this mean you are going to eventually get all your old plugins working on the current server?

One plug-in that would make more sense to me is to list shows you don't want to keep then once everyone had watched that episode then you delete the file since everyone watched it and won't watch it again. Some shows I will rewatch, so a list of shows to keep and a list of shows to trim/delete watched episodes would be a nice plugin.

**Comment by JamsRepos** [comment]
Can't wait for this to start working again, would love to play around with a subscription modal.

**Comment by TheOddPirate** [comment]
wow, there was way more changes to the jellyfin system then i would guess. This is gonna be some work to start it all over again, but in a week or two i think il have most of it up to date.

i actually never tested the subscription system i just ported it from emby, but if it works i hope u can give some feedback on it

**Comment by JamsRepos** [comment]
100%! I'm down to be a test subject for it all, let me know whenever you're working on getting it up to date. 

I know me and my mates wanting to use this will help you debug. 

> wow, there was way more changes to the jellyfin system then i would guess. This is gonna be some work to start it all over again, but in a week or two i think il have most of it up to date.
> 
> 
> 
> i actually never tested the subscription system i just ported it from emby, but if it works i hope u can give some feedback on it

**Comment by Protektor-Desura** [comment]
I'm more than willing to help test any and all of your plugins to get them working again.

**Comment by JamsRepos** [comment]
Has there been any update on this at all? :) I'm happy to help fund development if that is need be, would love to be able to put subscription based accounts on my server for my mates who want to help fund the project.

**Comment by Protektor-Desura** [comment]
I am guessing that nothing is going to get updated given the holiday is over and I assume he is back to school or whatever.

**Comment by MaDTaZ** [comment]
it is a shame but people have Real Life to do as well.  Hopefully he get some more time off.

**Comment by Protektor-Desura** [comment]
I'm not saying he should drop everything, just commenting that it doesn't appear he had time to do any work on any of the plugins over the holidays.

**Comment by MaDTaZ** [comment]
> I'm not saying he should drop everything, just commenting that it doesn't appear he had time to do any work on any of the plugins over the holidays.

Ya I wasn't thinking you were just know how it feel to be busy and the internet community can be demanding.  LOL

**Comment by TheOddPirate** [comment]
I wish i was busy, just lacking the motivation and feeling depressed lately, BUT ive had a good day today so i uploaded a fresh repo with some plugins. I just need to figure out how this manifest file works again now so i can test them 
https://github.com/n0tOdd/n0tFlix

if any of you can get it working by manualy installing please give me some feedback so i know how they work
